version: '3.7'
services:

    mysql_bundle_1:
      build:
        context: './docker/mysql'
        args:
          SYSTEM_TIMEZONE: ${SYSTEM_TIMEZONE}
      container_name: mysql_bundle_1
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: developer
        MYSQL_USER: developer
        MYSQL_PASSWORD: developer
        MYSQL_DATABASE: developer
      volumes:
        - ./docker/mysql/init:/docker-entrypoint-initdb.d
      restart: on-failure
      networks:
        - docker-core-bundle-1

    php_bundle_1:
        restart: on-failure
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            args:
                SYSTEM_TIMEZONE:            ${SYSTEM_TIMEZONE}
                PHP_XDEBUG_ENABLE:          ${PHP_XDEBUG_ENABLE}
                PHP_XDEBUG_MODE:            ${PHP_XDEBUG_MODE}
                PHP_XDEBUG_REMOTE_PORT:     ${PHP_XDEBUG_REMOTE_PORT}
                PHP_XDEBUG_REMOTE_ADDRESS:  ${PHP_XDEBUG_REMOTE_ADDRESS}
                PHP_XDEBUG_IDEKEY:          ${PHP_XDEBUG_IDEKEY}
        extra_hosts:
            # Ensure that host.docker.internal is correctly defined on Linux bez toga nece raditi debagovanje preko comandne linije
            # ubaciti CLI interpreter u setting / PHP -> CLI interpreter
            - host.docker.internal:host-gateway
        env_file:
            - .env
        container_name: php_bundle_1
        hostname: php_bundle_1
        volumes:
          - ./:/www
        working_dir: /www
        expose:
          - "9000"
        networks:
            - docker-core-bundle-1

networks:
    docker-core-bundle-1:
        external: true

